export const SEARCH_CATEGORIES = [
	'car dealer',
	'car rental',
	'car repair',
	'car wash',
	'electric vehicle charging station',
	'gas station',
	'parking',
	'rest stop',
	'corporate office',
	'farm',
	'ranch',
	'art gallery',
	'art studio',
	'auditorium',
	'cultural landmark',
	'historical place',
	'monument',
	'museum',
	'performing arts theater',
	'sculpture',
	'library',
	'preschool',
	'primary school',
	'school',
	'secondary school',
	'university',
	'adventure sports center',
	'amphitheatre',
	'amusement center',
	'amusement park',
	'aquarium',
	'banquet hall',
	'barbecue area',
	'botanical garden',
	'bowling alley',
	'casino',
	'childrens camp',
	'comedy club',
	'community center',
	'concert hall',
	'convention center',
	'cultural center',
	'cycling park',
	'dance hall',
	'dog park',
	'event venue',
	'ferris wheel',
	'garden',
	'hiking area',
	'historical landmark',
	'internet cafe',
	'karaoke',
	'marina',
	'movie rental',
	'movie theater',
	'national park',
	'night club',
	'observation deck',
	'off roading area',
	'opera house',
	'park',
	'philharmonic hall',
	'picnic ground',
	'planetarium',
	'plaza',
	'roller coaster',
	'skateboard park',
	'state park',
	'tourist attraction',
	'video arcade',
	'visitor center',
	'water park',
	'wedding venue',
	'wildlife park',
	'wildlife refuge',
	'zoo',
	'public bath',
	'public bathroom',
	'stable',
	'accounting',
	'atm',
	'bank',
	'acai shop',
	'afghani restaurant',
	'african restaurant',
	'american restaurant',
	'asian restaurant',
	'bagel shop',
	'bakery',
	'bar',
	'bar and grill',
	'barbecue restaurant',
	'brazilian restaurant',
	'breakfast restaurant',
	'brunch restaurant',
	'buffet restaurant',
	'cafe',
	'cafeteria',
	'candy store',
	'cat cafe',
	'chinese restaurant',
	'chocolate factory',
	'chocolate shop',
	'coffee shop',
	'confectionery',
	'deli',
	'dessert restaurant',
	'dessert shop',
	'diner',
	'dog cafe',
	'donut shop',
	'fast food restaurant',
	'fine dining restaurant',
	'food court',
	'french restaurant',
	'greek restaurant',
	'hamburger restaurant',
	'ice cream shop',
	'indian restaurant',
	'indonesian restaurant',
	'italian restaurant',
	'japanese restaurant',
	'juice shop',
	'korean restaurant',
	'lebanese restaurant',
	'meal delivery',
	'meal takeaway',
	'mediterranean restaurant',
	'mexican restaurant',
	'middle eastern restaurant',
	'pizza restaurant',
	'pub',
	'ramen restaurant',
	'restaurant',
	'sandwich shop',
	'seafood restaurant',
	'spanish restaurant',
	'steak house',
	'sushi restaurant',
	'tea house',
	'thai restaurant',
	'turkish restaurant',
	'vegan restaurant',
	'vegetarian restaurant',
	'vietnamese restaurant',
	'wine bar',
	'administrative area level 1',
	'administrative area level 2',
	'country',
	'locality',
	'postal code',
	'school district',
	'city hall',
	'courthouse',
	'embassy',
	'fire station',
	'government office',
	'local government office',
	'neighborhood police station',
	'police',
	'post office',
	'chiropractor',
	'dental clinic',
	'dentist',
	'doctor',
	'drugstore',
	'hospital',
	'massage',
	'medical lab',
	'pharmacy',
	'physiotherapist',
	'sauna',
	'skin care clinic',
	'spa',
	'tanning studio',
	'wellness center',
	'yoga studio',
	'apartment building',
	'apartment complex',
	'condominium complex',
	'housing complex',
	'bed and breakfast',
	'budget japanese inn',
	'campground',
	'camping cabin',
	'cottage',
	'extended stay hotel',
	'farmstay',
	'guest house',
	'hostel',
	'hotel',
	'inn',
	'japanese inn',
	'lodging',
	'mobile home park',
	'motel',
	'private guest room',
	'resort hotel',
	'rv park',
	'beach',
	'church',
	'hindu temple',
	'mosque',
	'synagogue',
	'astrologer',
	'barber shop',
	'beautician',
	'beauty salon',
	'body art service',
	'catering service',
	'cemetery',
	'child care agency',
	'consultant',
	'courier service',
	'electrician',
	'florist',
	'food delivery',
	'foot care',
	'funeral home',
	'hair care',
	'hair salon',
	'insurance agency',
	'laundry',
	'lawyer',
	'locksmith',
	'makeup artist',
	'moving company',
	'nail salon',
	'painter',
	'plumber',
	'psychic',
	'real estate agency',
	'roofing contractor',
	'storage',
	'summer camp organizer',
	'tailor',
	'telecommunications service provider',
	'tour agency',
	'tourist information center',
	'travel agency',
	'veterinary care',
	'asian grocery store',
	'auto parts store',
	'bicycle store',
	'book store',
	'butcher shop',
	'cell phone store',
	'clothing store',
	'convenience store',
	'department store',
	'discount store',
	'electronics store',
	'food store',
	'furniture store',
	'gift shop',
	'grocery store',
	'hardware store',
	'home goods store',
	'home improvement store',
	'jewelry store',
	'liquor store',
	'market',
	'pet store',
	'shoe store',
	'shopping mall',
	'sporting goods store',
	'store',
	'supermarket',
	'warehouse store',
	'wholesaler',
	'arena',
	'athletic field',
	'fishing charter',
	'fishing pond',
	'fitness center',
	'golf course',
	'gym',
	'ice skating rink',
	'playground',
	'ski resort',
	'sports activity location',
	'sports club',
	'sports coaching',
	'sports complex',
	'stadium',
	'swimming pool',
	'airport',
	'airstrip',
	'bus station',
	'bus stop',
	'ferry terminal',
	'heliport',
	'international airport',
	'light rail station',
	'park and ride',
	'subway station',
	'taxi stand',
	'train station',
	'transit depot',
	'transit station',
	'truck stop',
];

export const GOOGLE_PLACES_SEARCH_TYPES = [
	'accounting',
	'airport',
	'amusement_park',
	'aquarium',
	'art_gallery',
	'atm',
	'bakery',
	'bank',
	'bar',
	'beauty_salon',
	'bicycle_store',
	'book_store',
	'bowling_alley',
	'bus_station',
	'cafe',
	'campground',
	'car_dealer',
	'car_rental',
	'car_repair',
	'car_wash',
	'casino',
	'cemetery',
	'church',
	'city_hall',
	'clothing_store',
	'convenience_store',
	'courthouse',
	'dentist',
	'department_store',
	'doctor',
	'drugstore',
	'electrician',
	'electronics_store',
	'embassy',
	'fire_station',
	'florist',
	'funeral_home',
	'furniture_store',
	'gas_station',
	'gym',
	'hair_care',
	'hardware_store',
	'hindu_temple',
	'home_goods_store',
	'hospital',
	'insurance_agency',
	'jewelry_store',
	'laundry',
	'lawyer',
	'library',
	'light_rail_station',
	'liquor_store',
	'local_government_office',
	'locksmith',
	'lodging',
	'meal_delivery',
	'meal_takeaway',
	'mosque',
	'movie_rental',
	'movie_theater',
	'moving_company',
	'museum',
	'night_club',
	'painter',
	'park',
	'parking',
	'pet_store',
	'pharmacy',
	'physiotherapist',
	'plumber',
	'police',
	'post_office',
	'primary_school',
	'real_estate_agency',
	'restaurant',
	'roofing_contractor',
	'rv_park',
	'school',
	'secondary_school',
	'shoe_store',
	'shopping_mall',
	'spa',
	'stadium',
	'storage',
	'store',
	'subway_station',
	'supermarket',
	'synagogue',
	'taxi_stand',
	'tourist_attraction',
	'train_station',
	'transit_station',
	'travel_agency',
	'university',
	'veterinary_care',
	'zoo',
] as const;

export type GooglePlacesSupportedType =
	(typeof GOOGLE_PLACES_SEARCH_TYPES)[number];
